# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Eden Tsai
subtitle:
description: Eden Tsai - Blog
author: Eden Tsai
author_title: 'Programmer'
avatar: css/images/avatar.png
location: 'Taiwan, Taipei'
follow: https://github.com/edentsai/
email: edentsai231@gmail.com
language: en
timezone: Asia/Taipei
since: 2000 # The start year showing in your copyright section.

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.edentsai.net
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
### hexo-clean-css: https://github.com/hexojs/hexo-clean-css
clean_css:
  exclude:

### hexo-generator-archive: https://github.com/hexojs/hexo-generator-archive
archive_generator:
  per_page: 10
  yearly: true
  monthly: true

### hexo-generator-category: https://github.com/hexojs/hexo-generator-category
category_generator:
  per_page: 10


### hexo-generator-feed: https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

### hexo-generator-index: https://github.com/hexojs/hexo-generator-index
index_generator:
  per_page: 10
  order_by: -date

### hexo-generator-search: https://github.com/PaicHyperionDev/hexo-generator-search
search:
  path: search.xml
  field: post

### hexo-generator-seo-friendly-sitemap: https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml

### hexo-generator-tag: https://github.com/hexojs/hexo-generator-tag
tag_generator:
  per_page: 10

### hexo-html-minifier: https://github.com/hexojs/hexo-html-minifier
html_minifier:
  exclude:

### hexo-imagemin: https://github.com/vseventer/hexo-imagemin
imagemin:
  enable     : true
  interlaced : false
  multipass  : false
  optimizationLevel: 2
  pngquant   : false
  progressive: false

### hexo-toc: https://github.com/bubkoo/hexo-toc
toc:
  maxDepth: 3

### hexo-uglify: https://github.com/hexojs/hexo-uglify
uglify:
  mangle: true
  output:
  compress:
  exclude:

## Themes: http://hexo.io/themes/
theme: icarus

## Disqus
disqus_shortname: edentsai

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:edentsai/edentsai.github.io.git
  branch: master
